services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: weather
    container_name: weather-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
